# Image
# version: "3.9"
# services:
#   spring:
#     platform: linux/amd64
#     image: andrewt51/spring
#   api:
#     platform: linux/amd64
#     depends_on:
#       - mongodb
#     image: andrewt51/api
#   cra:
#     platform: linux/amd64
#     depends_on:
#       - reverse-proxy
#     image: andrewt51/cra
#   nxtjs:
#     platform: linux/amd64
#     depends_on:
#       - reverse-proxy
#     image: andrewt51/nxtjs
#   veet:
#     platform: linux/amd64
#     depends_on:
#       - reverse-proxy
#     image: andrewt51/veet
#   mongodb:
#     image: mongo:latest
#   reverse-proxy:
#     restart: always
#     build: .
#     ports:
#       - "80:80"

# Build
version: "3.9"
services:
  spring:
    build: ./server-applications/spring
  api:
    depends_on:
      - mongodb
    build: ./server-applications/api
  cra:
    depends_on:
      - reverse-proxy
    build: ./frontend-applications/cra
  nxtjs:
    depends_on:
      - reverse-proxy
    build: ./frontend-applications/nxtjs
  veet:
    depends_on:
      - reverse-proxy
    build: ./frontend-applications/veet
  mongodb:
    image: mongo:latest
  reverse-proxy:
    restart: always
    build: .
    ports:
      - "80:80"

# Image
# version: "3.9"
# services:
#   # spring:
#   #   image: andrewt51/spring
#   api:
#     platform: linux/amd64
#     depends_on:
#       - mongodb
#     image: andrewt51/api
#   cra:
#     platform: linux/amd64
#     depends_on:
#       - reverse-proxy
#     image: andrewt51/cra
    
#   # nxtjs:
#   #   depends_on:
#   #     - reverse-proxy
#   #   image: andrewt51/nxtjs
#   veet:
#     platform: linux/amd64
#     depends_on:
#       - reverse-proxy
#     image: andrewt51/veet
#   mongodb:
#     image: mongo:latest
#   reverse-proxy:
#     restart: always
#     build: .
#     ports:
#       - "80:80"